---
AWSTemplateFormatVersion: 2010-09-09
#Parameters provided inline with default values
Parameters:
  awsRegion:
    Description: Provided AWSRegion
    Type: String
    Default: us-east-1
  cidrBlock:
    Description: Provided cidr block
    Type: String
    Default: 10.0.0.0/16
  subnetCidrBlock:
    Description: Provided AWSRegion
    Type: String
    Default: 10.0.0.0/16
  vpcName:
    Description: Provided Vpc Name
    Type: String
    Default: bajaj-m-vpc
# Resources block
Resources:
  myVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref cidrBlock
      Tags:
        - Key: Name
          Value: !Ref vpcName
  # Subnets
  subnet1: 
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref awsRegion
      CidrBlock: !Select [ 0, !Cidr [ !Ref subnetCidrBlock, 3, 8 ]]
      VpcId: !Ref myVpc
      Tags:
        - Key: Name
          Value: !Join ["-",[!Ref vpcName,!Ref awsRegion,subnet1]]
  subnet2: 
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select 
        - 1
        - Fn::GetAZs: !Ref awsRegion
      CidrBlock: !Select [ 1, !Cidr [ !Ref subnetCidrBlock, 2, 8 ]]
      VpcId: !Ref myVpc
      Tags:
        - Key: Name
          Value: !Join ["-",[!Ref vpcName,!Ref awsRegion,subnet2]]
  subnet3: 
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select 
        - 3
        - Fn::GetAZs: !Ref awsRegion
      CidrBlock: !Select [ 2, !Cidr [ !Ref subnetCidrBlock, 3, 8 ]]
      VpcId: !Ref myVpc
      Tags:
        - Key: Name
          Value: !Join ["-",[!Ref vpcName,!Ref awsRegion,subnet3]]
  # Internet Gateway
  internetGateway:
    Type: AWS::EC2::InternetGateway
  # Attaching gateway to VPC
  attachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVpc
      InternetGatewayId: !Ref internetGateway
  # Route table
  routeTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVpc
      Tags:
        - Key: Name
          Value: !Join ["-",[!Ref vpcName,!Ref awsRegion,route-table]]
  # Attaching subnets to route table
  subnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref subnet1
      RouteTableId: !Ref routeTable
  subnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref subnet2
      RouteTableId: !Ref routeTable
  subnetRouteTableAssociation3:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref subnet3
      RouteTableId: !Ref routeTable
  # Public Route
  publicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref routeTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref internetGateway